# Datasource
spring.datasource.url=jdbc:mysql://localhost:3306/law?createDatabaseIfNotExist=true
spring.datasource.username=law
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.access-token-validity=900000
jwt.secret-key=5368566D597133743677397A24432646294A404E635166546A576E5A72347537
jwt.secret-refresh-key=ES8SNaJqxSQ16RvVsDkMDuZrbjLiSfZMsAePtFS9edjbY37920suNnQ5nSe7uKDJ

# CORS
app.cors.allowed-domain=http://localhost:3000

# Server
server.port=8080